/*
Copyright 2019 Replicated, Inc..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/replicatedhq/kots/kotskinds/apis/kots/v1beta1"
	scheme "github.com/replicatedhq/kots/kotskinds/client/kotsclientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PrivateLicensesGetter has a method to return a PrivateLicenseInterface.
// A group's client should implement this interface.
type PrivateLicensesGetter interface {
	PrivateLicenses(namespace string) PrivateLicenseInterface
}

// PrivateLicenseInterface has methods to work with PrivateLicense resources.
type PrivateLicenseInterface interface {
	Create(ctx context.Context, privateLicense *v1beta1.PrivateLicense, opts v1.CreateOptions) (*v1beta1.PrivateLicense, error)
	Update(ctx context.Context, privateLicense *v1beta1.PrivateLicense, opts v1.UpdateOptions) (*v1beta1.PrivateLicense, error)
	UpdateStatus(ctx context.Context, privateLicense *v1beta1.PrivateLicense, opts v1.UpdateOptions) (*v1beta1.PrivateLicense, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.PrivateLicense, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.PrivateLicenseList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.PrivateLicense, err error)
	PrivateLicenseExpansion
}

// privateLicenses implements PrivateLicenseInterface
type privateLicenses struct {
	client rest.Interface
	ns     string
}

// newPrivateLicenses returns a PrivateLicenses
func newPrivateLicenses(c *KotsV1beta1Client, namespace string) *privateLicenses {
	return &privateLicenses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the privateLicense, and returns the corresponding privateLicense object, and an error if there is any.
func (c *privateLicenses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.PrivateLicense, err error) {
	result = &v1beta1.PrivateLicense{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("privatelicenses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PrivateLicenses that match those selectors.
func (c *privateLicenses) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.PrivateLicenseList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.PrivateLicenseList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("privatelicenses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested privateLicenses.
func (c *privateLicenses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("privatelicenses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a privateLicense and creates it.  Returns the server's representation of the privateLicense, and an error, if there is any.
func (c *privateLicenses) Create(ctx context.Context, privateLicense *v1beta1.PrivateLicense, opts v1.CreateOptions) (result *v1beta1.PrivateLicense, err error) {
	result = &v1beta1.PrivateLicense{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("privatelicenses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(privateLicense).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a privateLicense and updates it. Returns the server's representation of the privateLicense, and an error, if there is any.
func (c *privateLicenses) Update(ctx context.Context, privateLicense *v1beta1.PrivateLicense, opts v1.UpdateOptions) (result *v1beta1.PrivateLicense, err error) {
	result = &v1beta1.PrivateLicense{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("privatelicenses").
		Name(privateLicense.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(privateLicense).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *privateLicenses) UpdateStatus(ctx context.Context, privateLicense *v1beta1.PrivateLicense, opts v1.UpdateOptions) (result *v1beta1.PrivateLicense, err error) {
	result = &v1beta1.PrivateLicense{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("privatelicenses").
		Name(privateLicense.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(privateLicense).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the privateLicense and deletes it. Returns an error if one occurs.
func (c *privateLicenses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("privatelicenses").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *privateLicenses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("privatelicenses").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched privateLicense.
func (c *privateLicenses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.PrivateLicense, err error) {
	result = &v1beta1.PrivateLicense{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("privatelicenses").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
